[package]
name = "beryl-wifi"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["process", "io-util"] }
tracing.workspace = true
serde.workspace = true
beryl-config = { path = "../beryl-config" }
regex = "1"
